<?php

/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
// genesis();

get_header();

// Start the loop to display the post content
if (have_posts()) :
	while (have_posts()) :
		the_post();
?>

		<div class="page-layout-desktop">
			<div class="mb-blogs">
				<div class="blogDetails-wrapper">
					<h1 class="blog-heading">
						<?php the_title(); ?>
					</h1>
					<span class="blog-date"><?php echo get_the_date('j F Y', get_the_ID()) ?></span>
					<div class="blog-actions">
						<a href="">
							<img src="https://img10.hkrtcdn.com/mb/static/media/common/fb.svg" alt="">
						</a>
						<a href="">
							<img src="https://img10.hkrtcdn.com/mb/static/media/common/twitter.svg" alt="">
						</a>
					</div>
					<?php
					if (has_post_thumbnail()) :
						the_post_thumbnail('large', ['title' => get_the_title()]);
					else : ?>
						<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/default.jpg" alt="default" title="default" class="hero-image" /> <?php
																																							endif;
																																								?>
					<div class="content-wrapper">
						<?php the_excerpt(); ?>
						<div class="section-container">
							<?php the_content(); ?>
						</div>
					</div>
				</div>
				<div class="article-wrapper">
					<div class="HK-pagecontainer">
						<div class="topHeading">SIMILAR ARTICLES</div>
						<div class="top-articles-wrapper">
							<!-- Similar Posts Loop -->
							<?php
							$similar_posts = get_posts(array(
								'numberposts' => 4,
								'orderby' => 'rand',
								'post_type' => 'post',
								'post_status' => 'publish',
								'tax_query' => array(
									array(
										'taxonomy' => 'category',
										'field' => 'id',
										'terms' => wp_get_post_categories(get_the_ID())
									)
								),
								'exclude' => get_the_ID()
							));

							if ($similar_posts) :
								foreach ($similar_posts as $post) : setup_postdata($post);
							?>
									<div class="SimilarArticleCard-Container-wrapper">
										<div class="SimilarArticleCard-Container">
											<a href="<?php the_permalink(); ?>">
												<img src="<?php the_post_thumbnail_url(); ?>" alt="">
												<div class="content">
													<div class="heading"><?php the_title(); ?></div>
													<div class="date"><?php echo get_the_date('j F Y', get_the_ID()) ?></div>
												</div>
											</a>
										</div>
									</div>
							<?php
								endforeach;
								wp_reset_postdata();
							endif;
							?>
							<!-- End of Similar Posts Loop -->
						</div>
						<a href="/" class="mb-button-v-a">
							<button class="mb-button-view-all">View All Articles</button>
						</a>
					</div>
				</div>

			</div>
		</div>

<?php
	endwhile;
endif;

get_footer();
?>
